version: "3"

networks:
  nextcloud_network:
    external: false

services:

  redis:
    image: 'docker.io/redis:latest'
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - nextcloud_network
  db:
    image: docker.io/mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    env_file:
      - db.env
    networks:
      - nextcloud_network

  app:
    build: 
      context: ./app
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - nextcloud_network
    depends_on:
      - redis
      - db

